brew update

# Taps
brew tap homebrew/core
brew tap caskroom/cask

brew 'git'
brew 'vim'
brew 'curl'
brew 'wget'
brew 'npm'
brew 'openssl'

cask 'alfred'
cask 'iterm2'
cask 'slack'
cask 'virtualbox'
cask 'docker'
cask 'google-chrome'

brew cleanup
