brew update
brew tap caskroom/cask

brew install 'git'
brew install 'npm'
brew install 'vim'
brew install 'wget'
brew install 'openssl'

brew cask install 'docker'
brew cask install 'alfred'
brew cask install 'iterm2'

brew cleanup
