brew update

# Taps
brew tap homebrew/core
brew tap caskroom/cask
brew tap caskroom/fonts

brew 'git'
brew 'vim'
brew 'curl'
brew 'wget'
brew 'npm'
brew 'openssl'
brew 'zsh'

cask 'alfred'
cask 'iterm2'
cask 'slack'
cask 'virtualbox'
cask 'docker'
cask 'google-chrome'
cask 'font-hack-nerd-font'

brew cleanup
